stages:
- name: deploy
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: demandcluster/test:v1
      pushRemote: true
      registry: harbor.demandcluster.com
timeout: 60
notification: {}
