stages:

- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: demandcluster/core:staging
      pushRemote: true
      registry: harbor.demandcluster.com
    env:
      NPM_USER: demandcluster
    envFrom:
    - sourceName: cicd
      sourceKey: NPM_TOKEN
timeout: 60
notification: {}
