stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: demandcluster/core:staging
      pushRemote: true
      registry: harbor.demandcluster.com
    env:
      HOME: /home/jenkins
      NPM_CONFIG_CACHE: /home/jenkins/.npm
      NPM_USER: demandcluster
    envFrom:
    - sourceName: cicd
      sourceKey: NPM_TOKEN
- name: Deploy Staging Server
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
