stages:
- name: Install
  steps:
  - runScriptConfig:
      image: node:12-alpine
      shellScript: which python && npm install -g npm-cli-login && npm set registry https://npm.demandcluster.com && npm-cli-login --quotes && npm install && which python
    env:
      HOME: /home/jenkins
      NPM_CONFIG_CACHE: /home/jenkins/.npm
      NPM_EMAIL: devops@demandcluster.com
      NPM_REGISTRY: https://npm.demandcluster.com
      NPM_USER: demandcluster
    envFrom:
    - sourceName: cicd
      sourceKey: NPM_TOKEN
      targetKey: NPM_TOKEN
    - sourceName: cicd
      sourceKey: NPM_PASS
      targetKey: NPM_PASS
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: demandcluster/core:staging
      pushRemote: true
      registry: harbor.demandcluster.com
    env:
      HOME: /home/jenkins
      KUBECTL_ACTION: replace
      NPM_CONFIG_CACHE: /home/jenkins/.npm
      NPM_USER: demandcluster
    envFrom:
    - sourceName: cicd
      sourceKey: NPM_TOKEN
- name: Deploy Staging Server
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
branch:
  include:
  - staging
notification: {}
