stages:
- name: toestand
  steps:
  - runScriptConfig:
      image: ubuntu
      shellScript: npm test
- name: build
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: npm lint
- name: morebuild
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: npm build
- name: deploy
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: demandcluster/test:v1
      pushRemote: true
      registry: harbor.demandcluster.com
timeout: 60
notification: {}
