stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: demandcluster/core:staging
      pushRemote: true
      registry: harbor.demandcluster.com
    env:
      HOME: /home/jenkins
      KUBECTL_ACTION: replace
      NPM_CONFIG_CACHE: /home/jenkins/.npm
      NPM_USER: demandcluster
      PLUGIN_BUILD_ARGS: NPM_ARG=$NPM_TOKEN
    envFrom:
    - sourceName: cicd
      sourceKey: NPM_TOKEN
      targetKey: NPM_TOKEN
    - sourceName: cicd
      sourceKey: NPM_PASS
      targetKey: NPM_PASS
- name: Deploy Staging Server
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
branch:
  include:
  - staging
notification: {}
