stages:
- name: deploy
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: demandcluster/test:v1
      pushRemote: true
      registry: 127.0.0.1:34431
timeout: 60
notification: {}
