stages:
- name: Install
  steps:
  - runScriptConfig:
      image: node:12
      shellScript: |-
        npm update
        npm install
- name: Lint
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: npm run lint
- name: deploy
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: demandcluster/test:v1
      pushRemote: true
      registry: harbor.demandcluster.com
timeout: 60
notification: {}
