# This docker-compose file is used to run the project in Docker for development.
# The local files are mounted into the created container.
#
# Usage:
#  ln -s docker-compose.dev.yml docker-compose.override.yml
#  docker-compose up [-d]
#
# To go back to running the published image:
#  rm docker-compose.override.yml

version: '2'

services:
  api:
    image: reactioncommerce/node-dev:14.15.0-v1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.demandjs-api.rule=Host(`api.demandcluster.com`)"
      - "traefik.http.routers.demandjs-api.tls=true"
      - "traefik.http.routers.demandjs-api.entrypoints=websecure"
      - "traefik.http.routers.demandjs-api.service=demandjs-api-service"
      - "traefik.http.services.demandjs-api-service.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"

    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/usr/local/src/app:cached
      - api_node_modules:/usr/local/src/app/node_modules # do not link node_modules in, and persist it between dc up runs
    restart: always

volumes:
  mongo-db4:
  api_node_modules:
